# Generated by Django 6.0.1 on 2026-03-07 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('synced_at', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hms_department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('rate', models.FloatField(blank=True, null=True)),
                ('department', models.CharField(blank=True, max_length=10, null=True)),
                ('avgcontime', models.IntegerField(blank=True, null=True)),
                ('qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('synced_at', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hms_doctors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DoctorTiming',
            fields=[
                ('slno', models.BigIntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('t1', models.FloatField(blank=True, null=True)),
                ('t2', models.FloatField(blank=True, null=True)),
                ('synced_at', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hms_doctorstiming',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HospitalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(blank=True, max_length=200, null=True)),
                ('address1', models.CharField(blank=True, max_length=200, null=True)),
                ('synced_at', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hms_hospital_info',
                'managed': False,
            },
        ),
    ]
