# Generated by Django 6.0.1 on 2026-03-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_email_appointment_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='slot_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
