# Generated by Django 6.0.1 on 2026-03-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_add_query_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='appointment',
            name='apt_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='appointment',
            name='apt_doc_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='appointment',
            name='apt_status_idx',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected')], default='accepted', max_length=20),
        ),
    ]
