# Generated by Django 6.0.1 on 2026-03-27 06:49

from django.db import migrations


def migrate_pending_to_accepted(apps, schema_editor):
    """Migrate all pending appointments to accepted"""
    Appointment = apps.get_model('appointments', 'Appointment')
    Appointment.objects.filter(status='pending').update(status='accepted')


def reverse_migration(apps, schema_editor):
    """Reverse: migrate accepted appointments back to pending (only those that were migrated)"""
    # Note: We can't reliably reverse this, so we do nothing
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_remove_appointment_apt_created_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_pending_to_accepted, reverse_migration),
    ]
