# Generated by Django 6.0.1 on 2026-03-12 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='profile_photo',
        ),
    ]
